version: "3"

services:
  app:
    container_name: app
    image: app
    restart: always
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: [ "python3", "manage.py", "runserver", "0.0.0.0:8000" ]